[theme]
primaryColor = "#99582f"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f5f5"
textColor = "#111b26"
font = "sans serif"

[server]
headless = true
enableCORS = true
enableXsrfProtection = true
runOnSave = false
fileWatcherType = "none"

[browser]
gatherUsageStats = false
